# Generated by Django 2.2.1 on 2019-05-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=280)),
                ('lang', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel_api.User')),
            ],
        ),
    ]
