# Generated by Django 2.2.1 on 2019-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0002_auto_20190506_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='lang',
            field=models.CharField(default='', max_length=5),
        ),
    ]
