# Generated by Django 2.2.1 on 2019-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0003_tweet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
