# Generated by Django 2.2.1 on 2019-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0004_tweet_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
