# Generated by Django 2.2.1 on 2019-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0007_tweet_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
