# Generated by Django 2.2.1 on 2019-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0013_auto_20190506_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
    ]
