# Generated by Django 2.2.1 on 2019-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0019_auto_20190508_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetInteractionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
