# Generated by Django 2.2.1 on 2019-05-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0020_auto_20190508_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='favorited',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted',
        ),
    ]
